plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id "org.jetbrains.kotlin.jvm" version "2.0.21"
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
    maven {
        name = "NeoForged"
        url = "https://maven.neoforged.net/releases"
    }
    maven {
        name = "kotlinforforge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
}

loom {
    mods {
        modid {
            sourceSet sourceSets.main
        }
    }

}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    neoForge("net.neoforged:neoforge:21.1.192")
//    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
//
//    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
//    modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
//
    modImplementation("thedarkcolour:kotlinforforge-neoforge:5.9.0")

    implementation 'net.kyori:adventure-text-serializer-legacy:4.17.0'
    modImplementation 'net.kyori:adventure-platform-neoforge:6.0.1'
    implementation "net.kyori:adventure-api:4.17.0"

    include 'net.kyori:adventure-platform-neoforge:6.0.1'
    include 'net.kyori:adventure-text-serializer-legacy:4.17.0'
    include "net.kyori:adventure-api:4.17.0"

    compileOnly 'net.luckperms:api:5.4'
}

processResources {
    inputs.property "version", project.version

    filesMatching("neoforge.mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = 21
    }
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

