modLoader="kotlinforforge"
loaderVersion="[5.3,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/navneetset/pebbles-crate"

[[mods]]
modId="pebbles_crate"
version="1.1.3-1.21.1" #"${version}"
displayName="Pebble's Crates"
authors="navneetset"
logoFile= "../assets/pebbles_crate/icon.webp"
description='''
Lootcrate mod for your lootcrate needs!
'''

[[dependencies.pebbles_crate]]
modId="neoforge"
mandatory=true
versionRange="[21.1.84,)"
ordering="NONE"
side="BOTH"

[[dependencies.pebbles_crate]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"